### ISSUE TITLE
why

### ISSUE THREAD

**Issue by 3052** [braheezy/shine-mp3#4]
whats the point of an MP3 module in 2023? I dont mean this an as insult, I just think it would be helpful to clarify in the Readme or similar. for example, YouTube hasnt used MP3 in years, they use Opus or AAC.

**Comment by KMastroluca** [comment]
Mp3 is used extensively still in audio engineering/music production, specifically usually for client renders or reference tracks and occasionally as audio assets like samples or sound kits and therefore building tools and VST plugins that support encoding and decoding this format is still extremely relevant.

**Comment by braheezy** [comment]
I had a personal need on a different Go project for encoding raw audio data to MP3 on a Windows platform. I couldn't figure out how to build any existing C-based solutions for Windows.
