### ISSUE TITLE
Revisit the licensing for this port

### ISSUE THREAD

**Issue by rainydaysavings** [braheezy/shine-mp3#5]
You should take a closer look before porting a project and license it under a different license.

The Shine MP3 encoder is licensed under the GNU General Public License (GPL), version 2. This can be seen under [COPYING](https://github.com/toots/shine/blob/main/COPYING).

The GPL requires any derivative works to also be released under the GPL. The GPL is strict in its copyleft provisions, meaning you can't relicense it under a more permissive license like MIT without explicit permission from the original authors.

This should be taken as a friendly heads up, you did a great job. Just be careful with this.

**Comment by braheezy** [comment]
Thanks for catching that!
